name: Danger

on: pull_request

jobs:
  danger:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_11.4.app

    - name: Cache RubyGems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Cache Mint Builds
      uses: actions/cache@v1
      with:
        path: ${{ env.MINT_PATH }}
        key: ${{ runner.os }}-mint-build-${{ env.SWIFTLINT_VERSION }}
        restore-keys: |
          ${{ runner.os }}-mint-build-
  
    - name: Cache Mint Links
      uses: actions/cache@v1
      with:
        path: ${{ env.MINT_LINK_PATH }}
        key: ${{ runner.os }}-mint-link-${{ env.SWIFTLINT_VERSION }}
        restore-keys: |
          ${{ runner.os }}-mint-link-

    - name: Bundle install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Install Mint and Packages
      run: |
        brew install mint
        mint install realm/SwiftLint@${{ env.SWIFTLINT_VERSION }}

    - name: Run Danger
      run: bundle exec danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    env:
      MINT_PATH: ${{ github.workspace }}/mint
      MINT_LINK_PATH: ${{ github.workspace }}/mint/bin
      SWIFTLINT_VERSION: 0.39.1
